---
title: "Rural and Urban Census Data"
author: "Madison Yonash"
date: "2023-09-27"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
data <- read.table(file = "C:/Users/madis/Documents/pharmacy-misc/Urban Census Data.txt", 
                   sep = "|",
                   header = T,
                   colClasses = "character")
```

```{r}
glimpse(data)
```

```{r}
cageo <- read.table("C:/Users/madis/Documents/pharmacy-misc/cageo2020.pl",
                    sep = "|",
                    header = F,
                    fill = T,
                    colClasses = "character"
                    )
```

```{r}
glimpse(cageo)
```


```{r}
santaclara <- cageo %>% 
  filter(V95 == "CT") %>% 
  select('V2', 'V13', 'V15', 'V87', 'V91') %>% 
  rename('State' = 'V2',
         'StateCode' = 'V13',
         'CountyCode' = 'V15',
         'CTCode' = 'V87',
         'Population' = 'V91'
         ) %>% 
  transform(Population = as.numeric(Population)) %>% 
  unite(GeoID, c('StateCode', 'CountyCode', 'CTCode'), sep = "", remove = FALSE)
santaclara$GeoID <- substr(santaclara$GeoID, 0, 9)
santaclara
```


```{r}
totalPop <- santaclara %>% 
  group_by(GeoID) %>% 
  summarize(Population = sum(Population))
totalPop
```


```{r}
data$GEOID <- substr(data$GEOID, 0, 9)
glimpse(data)
```

```{r}
data <- data%>% 
  transform(X2020_POP = as.numeric(X2020_POP))
```

```{r}
urbanCT <- data  %>% 
  aggregate(X2020_POP~GEOID, FUN=sum) %>% 
  rename('GeoID' = 'GEOID',
         'UrbanPop' = 'X2020_POP'
         )
urbanCT
```


```{r}
mergedDF <- merge(x = totalPop, y = urbanCT, by = "GeoID", all.x=T)
mergedDF
```

```{r}
for (i in 1:nrow(mergedDF)) {
   mergedDF$urbanPercent[i] <- mergedDF$UrbanPop[i] / mergedDF$Population[i]
}

mergedDF
```



```{r}
testdata <- data %>% 
  filter(STATE == "06",
         COUNTY == "013",
         TRACT == "3760"
           )

sum(testdata$X2020_POP) 
```

```{r}
testcageo <- cageo %>% 
  filter(V13 == "06",
         V15 == "085",
         V87 == "5121",
         V95 == "CT") %>% 
  transform(V91 = as.numeric(V91)) %>% 
  select('V2', 'V13', 'V15', 'V87', 'V91')
sum(testcageo$V91)
```
```{r}
testdata
```

```{r}
urban <- data %>% 
  select(STATE, COUNTY, TRACT, X2020_POP) %>% 
  transform(X2020_POP = as.numeric(X2020_POP))
urban$TRACT <- substr(urban$TRACT, 0, 4)
urban$GEOID <- paste(urban$STATE,urban$COUNTY,urban$TRACT, sep ="")
urban <- urban %>% 
  group_by(GEOID) %>% 
  mutate(TRACT_POP = sum(X2020_POP))  %>% 
  select(-X2020_POP) 
```

```{r}
urban <- urban %>% 
  unique()
```

```{r}

urban
```

```{r}
urbansort <- urban[order(urban$GEOID),]
urbansort

```

```{r}
totalpop <- cageo %>%  
  filter(V95 == "CT") %>% 
  select('V2', 'V13', 'V15', 'V87', 'V91') %>% 
  rename('STATENAME' = 'V2',
         'STATE' = 'V13',
         'COUNTY' = 'V15',
         'TRACT' = 'V87',
         'TOTAL_POP' = 'V91'
         ) %>% 
  transform(TOTAL_POP = as.numeric(TOTAL_POP)) %>% 
  unite(GEOID, c('STATE', 'COUNTY', 'TRACT'), sep = "", remove = FALSE)
totalpop$GEOID <- substr(totalpop$GEOID, 0, 9)
totalpop
```


```{r}
totalpop <- totalpop %>% 
  group_by(GEOID) %>% 
  mutate(TRACT_POP = sum(TOTAL_POP))  %>% 
  select(-TOTAL_POP) 
```

```{r}
totalpopsort <- totalpop[order(totalpop$GEOID),] 
totalpopsort
```

```{r}
totalpop <- totalpop %>% 
  unique()
```

```{r}
totalpop %>% 
  filter(GEOID == "	060133760")
```
```{r}
urbanrural <- merge(x = totalpop, y = urban, by = "GEOID", all.x=T) %>% 
  select(GEOID, TRACT_POP.x, TRACT_POP.y)
urbanrural
```

